name: Snayolo
version: '1.0'
main: de.cyklon.snayolo.Snayolo
api-version: 1.19
authors: [Cyklon73]
description: Das Plugin f端r das Grass Event von Snayo. (und denke immer daran SNAYOLO)
depend: [LightAPI]

permissions:
  snayolo.admin:
    description: admin rechte
    default: op
  snayolo.admin.edit-permissions:
    description: berechtigung um berechtigungen zu bearbeiten
    default: op

  snayolo.admin.world:
    description: berechtigung f端r /world
    default: op

  snayolo.admin.event:
    description: berechtigung f端r /event
    default: op

  snayolo.admin.reload-chunk:
    description: berechtigung f端r /reload-chunk
    default: op

commands:
  permission:
    permission: snayolo.admin.edit-permissions
  world:
    permission: snayolo.admin.world
  event:
    permission: snayolo.admin.event
  reload-chunk:
    permission: snayolo.admin.reload-chunk